'use client'

import { useState, useEffect } from 'react'
import { taskAPI } from '@/lib/api'

type TaskStatus = 'pending' | 'completed' | 'skipped' | 'partial'

interface Task {
  schedule_id: number
  task_id: number
  title: string
  description: string
  estimated_time_minutes: number
  category: string
  priority: string
  start_time?: string
  end_time?: string
  status: TaskStatus
}

interface DailyTasksProps {
  userId: number
}

export default function DailyTasks({ userId: propUserId }: DailyTasksProps) {
  const [tasks, setTasks] = useState<Task[]>([])
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0])
  const [autoGenerated, setAutoGenerated] = useState(false)

  useEffect(() => {
    loadTasks()
  }, [selectedDate, propUserId])

  useEffect(() => {
    // Auto-generate tasks for today if none exist
    if (!autoGenerated && selectedDate === new Date().toISOString().split('T')[0]) {
      checkAndAutoGenerate()
    }
  }, [propUserId])

  const checkAndAutoGenerate = async () => {
    try {
      const response = await api.post(`/automation/check-and-generate/${propUserId}`)
      if (response.data.status === 'success') {
        setAutoGenerated(true)
        await loadTasks()
      }
    } catch (error) {
      console.error('Auto-generation check failed:', error)
    }
  }

  const loadTasks = async () => {
    setLoading(true)
    try {
      const response = await taskAPI.getDaily(propUserId, selectedDate)
      setTasks(response.data.tasks || [])
    } catch (error) {
      console.error('Error loading tasks:', error)
    } finally {
      setLoading(false)
    }
  }

  const generateTasks = async () => {
    setGenerating(true)
    try {
      await api.post(`/automation/daily/${propUserId}`)
      await loadTasks()
    } catch (error) {
      console.error('Error generating tasks:', error)
      alert('Error generating tasks. Make sure you have created a goal first.')
    } finally {
      setGenerating(false)
    }
  }

  const updateTaskStatus = async (scheduleId: number, status: TaskStatus) => {
    try {
      await taskAPI.updateStatus(scheduleId, { status })
      setTasks(tasks.map(task => 
        task.schedule_id === scheduleId ? { ...task, status } : task
      ))
    } catch (error) {
      console.error('Error updating task:', error)
    }
  }

  const getCategoryColor = (category: string) => {
    const colors: Record<string, string> = {
      learning: 'bg-blue-100 text-blue-800',
      building: 'bg-green-100 text-green-800',
      health: 'bg-red-100 text-red-800',
      reflection: 'bg-purple-100 text-purple-800'
    }
    return colors[category] || 'bg-gray-100 text-gray-800'
  }

  return (
    <div className="bg-white rounded-lg shadow p-6">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-semibold">Daily Tasks</h2>
        <input
          type="date"
          value={selectedDate}
          onChange={(e) => setSelectedDate(e.target.value)}
          className="px-3 py-1 border border-gray-300 rounded-md text-sm"
        />
      </div>

      {tasks.length === 0 && !loading && (
        <div className="text-center py-8">
          <p className="text-gray-600 mb-4">No tasks for this day</p>
          <button
            onClick={generateTasks}
            disabled={generating}
            className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:bg-gray-400"
          >
            {generating ? 'Generating...' : 'Generate AI Tasks'}
          </button>
        </div>
      )}

      {loading && (
        <div className="text-center py-8">
          <p className="text-gray-600">Loading tasks...</p>
        </div>
      )}

      <div className="space-y-4">
        {tasks.map(task => (
          <div key={task.schedule_id} className="border rounded-lg p-4">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <h3 className="font-medium">{task.title}</h3>
                  {task.start_time && (
                    <span className="text-xs text-gray-500">
                      {task.start_time} - {task.end_time}
                    </span>
                  )}
                </div>
                <p className="text-sm text-gray-600 mt-1">{task.description}</p>
                <div className="flex gap-2 mt-2">
                  <span className={`text-xs px-2 py-1 rounded ${getCategoryColor(task.category)}`}>
                    {task.category}
                  </span>
                  <span className="text-xs px-2 py-1 rounded bg-gray-100 text-gray-800">
                    {task.estimated_time_minutes} min
                  </span>
                  <span className={`text-xs px-2 py-1 rounded ${
                    task.priority === 'high' ? 'bg-red-100 text-red-800' : 
                    task.priority === 'medium' ? 'bg-yellow-100 text-yellow-800' : 
                    'bg-green-100 text-green-800'
                  }`}>
                    {task.priority}
                  </span>
                </div>
              </div>
              
              <div className="flex gap-2 ml-4">
                <button
                  onClick={() => updateTaskStatus(task.schedule_id, 'completed')}
                  className={`px-3 py-1 text-sm rounded ${task.status === 'completed' ? 'bg-green-600 text-white' : 'bg-gray-200'}`}
                  title="Completed"
                >
                  ✓
                </button>
                <button
                  onClick={() => updateTaskStatus(task.schedule_id, 'partial')}
                  className={`px-3 py-1 text-sm rounded ${task.status === 'partial' ? 'bg-yellow-600 text-white' : 'bg-gray-200'}`}
                  title="Partial"
                >
                  ~
                </button>
                <button
                  onClick={() => updateTaskStatus(task.schedule_id, 'skipped')}
                  className={`px-3 py-1 text-sm rounded ${task.status === 'skipped' ? 'bg-red-600 text-white' : 'bg-gray-200'}`}
                  title="Skipped"
                >
                  ✗
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
